Operations = {
	Addition: 1,
	Backspace: 2,
	Clear: 3,
	ClearEntry: 4,
	Division: 5,
	Fraction: 6,
	Memory: 7,
	MemoryAddition: 8,
	MemoryClear: 9,
	MemoryRecall: 10,
	MemoryStore: 11,
	MemorySubtraction: 12,
	Multiplication: 13,
	Percent: 14,
	Point: 15,
	Result: 16,
	Square: 17,
	SquareRoot: 18,
	Subtraction: 19,
	Switch: 20
};